# Generated by Django 6.0.4 on 2026-04-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_dining_room_property_has_balcony_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('report_scope', models.CharField(choices=[('agency', 'Agency Report'), ('owner', 'Owner Report')], default='agency', max_length=20)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('agency_total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agency_total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agency_net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('owner_total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('owner_total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('owner_total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('owner_net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('property_count', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
