# Generated by Django 6.0.4 on 2026-04-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_agency'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('property', 'report_type', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='owner_payout',
        ),
    ]
