# Generated by Django 6.0.4 on 2026-04-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dining_room',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Full Kitchen'), (2, 'Semi Kitchen'), (3, 'No Kitchen')], null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='living_rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_status',
            field=models.CharField(choices=[('no', 'No Parking'), ('private', 'Private Garage'), ('street', 'On Street')], default='no', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
