# Generated by Django 6.0.4 on 2026-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='booking_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='nights',
            field=models.IntegerField(default=1),
        ),
    ]
