# Generated by Django 6.0.4 on 2026-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_financialrecord_booking_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='booking_source',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='nights',
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
