# Generated by Django 6.0.4 on 2026-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_remove_financialrecord_booking_source_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='booking_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
