# Generated by Django 6.0.4 on 2026-04-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_alter_financialrecord_unique_together_and_more'),
        ('properties', '0002_alter_property_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Cleaning', 'Cleaning'), ('WiFi', 'WiFi'), ('Electricity', 'Electricity'), ('Maintenance', 'Maintenance'), ('Supplies', 'Supplies'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('has_receipt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
