# Generated by Django 6.0.4 on 2026-05-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.AddField(
            model_name='owner',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='owner_pictures/'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
