# Generated by Django 6.0.4 on 2026-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('agency_manager', 'Agency Manager'), ('finance_staff', 'Finance Staff'), ('property_staff', 'Property Staff'), ('owner', 'Owner'), ('staff', 'Staff')], default='property_staff', max_length=20),
        ),
    ]
